/**
 * Generated by scripts/write-config.ts -- do not edit by hand.
 * Chain: 10143
 * Deployed: +058721-01-09T01:10:33.000Z
 * Built from commit: bca377af1776c9543b97fc3010c06e77cf6df239
 */
import { ERC8004 } from "./chain.ts";

export const ADDRESSES = {
  cardManager: "0xBE65B96d591840AaCBe591B327abe92Cddc64D24",
  spendGate: "0xE020378b873d10dB86f3a1FF5c781db58B034794",
  spendRouter: "0xFc5Eb559b062F48D8f5C7d04F01C07568eB43124",
  mockMerchantA: "0xdaf1f3fdc83e49BD4D50fDA1613c15D1C7552244",
  mockMerchantB: "0x51fA5af542179cDe11e517b377f7fc2e443D86e8",
  mockMerchantC: "0x0B0DFdc99265ACead416F9872B283EDD0D33b87A",
  reputationReader: "0xc86630cB8901ff7038e2Fa3b48C3b2E4d28e159e",
  /** Settlement token: real AUSD on this chain, not a mock we deployed. */
  paymentToken: "0xa9012a055bd4e0eDfF8Ce09f960291C09D5322dC",
  ausdFaucet: "0xd236c18D274E54FAccC3dd9DDA4b27965a73ee6C",
  ...ERC8004,
} as const;

export const DEPLOYMENT = {
  chainId: 10143,
  commit: "bca377af1776c9543b97fc3010c06e77cf6df239",
  deployedAt: "+058721-01-09T01:10:33.000Z",
} as const;
