/**
 * Generated by scripts/write-config.ts -- do not edit by hand.
 * Chain: 10143
 * Deployed: +058707-07-04T23:56:16.000Z
 * Built from commit: 4c91e57385ae63d7977145fd64e7538eb8a88a91
 */
import { ERC8004 } from "./chain.ts";

export const ADDRESSES = {
  mockUSD: "0x82acf5f99EA05e5BD6a1886B5cBA63dE1Fc15395",
  cardManager: "0xA00d6901676EA65D3Fc0920046877eB8505329B0",
  spendGate: "0x0dD6F49781Cca0D309F784209d3f2Dc5Ec1ac26e",
  spendRouter: "0x2d6C43F8D74501af8A386589137980F729a43cA1",
  mockMerchantA: "0x10AC2e0abEB38e24dE19Fc5d2e2DcA5D9EEeF14E",
  mockMerchantB: "0xBf7B5E80045Ed9408B02297ccd707b1e61901A1A",
  reputationReader: "0x07885e31E2d1291583d6c4fed220C970e1AE0247",
  ...ERC8004,
} as const;

export const DEPLOYMENT = {
  chainId: 10143,
  commit: "4c91e57385ae63d7977145fd64e7538eb8a88a91",
  deployedAt: "+058707-07-04T23:56:16.000Z",
} as const;
