/**
 * Generated by scripts/write-config.ts -- do not edit by hand.
 * Chain: 10143
 * Deployed: +058693-12-08T00:02:03.000Z
 * Built from commit: f23ef7ebc22c683d53f5df47cda23ff534908de1
 */
import { ERC8004 } from "./chain.ts";

export const ADDRESSES = {
  mockUSD: "0x4BEE0Ecd3FB0f65A8a6982E2b3abB8baA14d731F",
  cardManager: "0xbfe4A4F6de7eC6e5153C3742541Ab9C9811f9FE5",
  spendGate: "0x540d97563C111b91f087C846ba19578f6BBff157",
  spendRouter: "0xBA379a9f4cd0D774e3a4E4388E2FefD86ACC2714",
  mockMerchantA: "0xEb198C0092Ade3d3Cd22e33A950A1A39eaDfEF15",
  mockMerchantB: "0xbb6B254F08D1340c2F72F7E1725e2A243c38b645",
  reputationReader: "0x1dBFfDDDDEa7fAE6dF89BF5291a07405B62ba571",
  ...ERC8004,
} as const;

export const DEPLOYMENT = {
  chainId: 10143,
  commit: "f23ef7ebc22c683d53f5df47cda23ff534908de1",
  deployedAt: "+058693-12-08T00:02:03.000Z",
} as const;
