/**
 * Writes deployed addresses from the Foundry broadcast artifact into
 * `config/addresses.ts` and the README table.
 *
 * Deployed addresses are never copied by hand: a transposed character in an address is
 * invisible in review and fails only at runtime, usually in front of judges.
 *
 * Usage: node scripts/write-config.ts [--chain 10143]
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { execSync } from "node:child_process";
import { getAddress } from "viem";
import { ERC8004 } from "../config/chain.ts";

const chainId = process.argv.includes("--chain")
  ? process.argv[process.argv.indexOf("--chain") + 1]
  : "10143";
/** --dry-run reads the simulation artifact, so the generator can be tested before a real deploy. */
const dir = process.argv.includes("--dry-run") ? "dry-run/" : "";
const broadcastPath = `contracts/broadcast/Deploy.s.sol/${chainId}/${dir}run-latest.json`;

if (!existsSync(broadcastPath)) {
  console.error(`No broadcast artifact at ${broadcastPath}. Run the deploy script first.`);
  process.exit(1);
}

type BroadcastTx = {
  transactionType: string;
  contractName: string | null;
  contractAddress: string | null;
  hash: string | null;
};

const broadcast = JSON.parse(readFileSync(broadcastPath, "utf8")) as {
  transactions: BroadcastTx[];
  timestamp: number;
};

const deployed = new Map<string, string>();
const seen = new Map<string, number>();
for (const tx of broadcast.transactions) {
  if (tx.transactionType !== "CREATE" || !tx.contractName || !tx.contractAddress) continue;
  // Two MockMerchants are deployed; suffix repeats A, B, C... so neither is lost.
  const n = seen.get(tx.contractName) ?? 0;
  seen.set(tx.contractName, n + 1);
  const key = n === 0 && tx.contractName !== "MockMerchant"
    ? tx.contractName
    : `${tx.contractName}${String.fromCharCode(65 + n)}`;
  deployed.set(key, getAddress(tx.contractAddress));
}

if (deployed.size === 0) {
  console.error("Broadcast artifact contains no CREATE transactions.");
  process.exit(1);
}

const commit = (() => {
  try {
    return execSync("git rev-parse HEAD", { encoding: "utf8" }).trim();
  } catch {
    return "unknown";
  }
})();

const deployedAt = new Date(broadcast.timestamp * 1000).toISOString();

// --- config/addresses.ts -----------------------------------------------------
const entries = [...deployed.entries()]
  .map(([name, addr]) => `  ${name.charAt(0).toLowerCase()}${name.slice(1)}: "${addr}",`)
  .join("\n");

writeFileSync(
  "config/addresses.ts",
  `/**
 * Generated by scripts/write-config.ts -- do not edit by hand.
 * Chain: ${chainId}
 * Deployed: ${deployedAt}
 * Built from commit: ${commit}
 */
import { ERC8004 } from "./chain.ts";

export const ADDRESSES = {
${entries}
  ...ERC8004,
} as const;

export const DEPLOYMENT = {
  chainId: ${chainId},
  commit: "${commit}",
  deployedAt: "${deployedAt}",
} as const;
`,
);

// --- README table ------------------------------------------------------------
const explorer = "https://testnet.monadexplorer.com/address";
const rows = [
  ...[...deployed.entries()].map(([n, a]) => `| \`${n}\` | [\`${a}\`](${explorer}/${a}) | this deployment |`),
  `| \`IdentityRegistry\` | [\`${ERC8004.identityRegistry}\`](${explorer}/${ERC8004.identityRegistry}) | ERC-8004 project |`,
  `| \`ReputationRegistry\` | [\`${ERC8004.reputationRegistry}\`](${explorer}/${ERC8004.reputationRegistry}) | ERC-8004 project |`,
].join("\n");

const block = `<!-- DEPLOYED:START -->
Monad Testnet (chain \`${chainId}\`), deployed ${deployedAt} from commit \`${commit}\`.

| Contract | Address | Deployer |
|---|---|---|
${rows}

Regenerate with \`npm run write-config\` after any redeploy.
<!-- DEPLOYED:END -->`;

const readme = readFileSync("README.md", "utf8");
const updated = readme.replace(/<!-- DEPLOYED:START -->[\s\S]*?<!-- DEPLOYED:END -->/, block);
if (updated === readme) {
  console.error("Could not find DEPLOYED markers in README.md.");
  process.exit(1);
}
writeFileSync("README.md", updated);

console.log(`Wrote config/addresses.ts and README table for chain ${chainId} (commit ${commit.slice(0, 8)}):`);
for (const [name, addr] of deployed) console.log(`  ${name.padEnd(20)} ${addr}`);
